-- Inled baseline schema
-- Agreed conventions:
-- - UUID PKs generated by gen_random_uuid()
-- - Semantic integer columns are app-defined (no CHECK constraints)
-- - Multi-company capable tenancy model

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Tenant root
CREATE TABLE IF NOT EXISTS companies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

-- Company membership (a user can belong to multiple companies)
CREATE TABLE IF NOT EXISTS company_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  role integer NOT NULL,
  status integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  joined_at timestamptz,
  UNIQUE (company_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_company_members_user_id
  ON company_members (user_id);

-- Invitation flow for joining companies
CREATE TABLE IF NOT EXISTS invites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  email text NOT NULL,
  role integer NOT NULL,
  status integer NOT NULL,
  token_hash text NOT NULL,
  invited_by_user_id uuid NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  accepted_at timestamptz,
  accepted_user_id uuid
);

CREATE INDEX IF NOT EXISTS idx_invites_company_id
  ON invites (company_id);

CREATE INDEX IF NOT EXISTS idx_invites_email
  ON invites (email);

-- Collaborators / targets (linked_user_id optional)
CREATE TABLE IF NOT EXISTS people (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  display_name text NOT NULL,
  handle text NOT NULL,
  linked_user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_people_company_id
  ON people (company_id);

CREATE INDEX IF NOT EXISTS idx_people_handle
  ON people (handle);

-- Strategic ideation goals
CREATE TABLE IF NOT EXISTS ideation_goals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  title text NOT NULL,
  tag text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

-- Optional uniqueness proposed in discussion
CREATE UNIQUE INDEX IF NOT EXISTS uq_ideation_goals_company_tag
  ON ideation_goals (company_id, lower(tag));

-- Unified ledger line:
-- one directed commitment, viewed as an "objective" by the target
-- and as an "expectation" by the writer.
CREATE TABLE IF NOT EXISTS expectations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  ideation_goal_id uuid REFERENCES ideation_goals(id) ON DELETE RESTRICT,
  writer_user_id uuid NOT NULL,
  target_person_id uuid NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  title text NOT NULL,
  summary text NOT NULL,
  deadline_label text,
  deadline_at timestamptz,
  progress integer,
  expectation_status integer NOT NULL,
  expectation_visibility integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_expectations_company_writer
  ON expectations (company_id, writer_user_id);

CREATE INDEX IF NOT EXISTS idx_expectations_company_target
  ON expectations (company_id, target_person_id);

CREATE INDEX IF NOT EXISTS idx_expectations_company_status
  ON expectations (company_id, expectation_status);

CREATE INDEX IF NOT EXISTS idx_expectations_company_goal
  ON expectations (company_id, ideation_goal_id);

-- Reusable tag dictionary per company
CREATE TABLE IF NOT EXISTS expectation_tags (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_expectation_tags_company_name
  ON expectation_tags (company_id, lower(name));

-- Many-to-many relation: one expectation can have many tags
CREATE TABLE IF NOT EXISTS expectation_tag_links (
  expectation_id uuid NOT NULL REFERENCES expectations(id) ON DELETE CASCADE,
  tag_id uuid NOT NULL REFERENCES expectation_tags(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (expectation_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_expectation_tag_links_tag_id
  ON expectation_tag_links (tag_id);

-- Audit trail for commitment lifecycle transitions
CREATE TABLE IF NOT EXISTS expectation_events (
  id bigserial PRIMARY KEY,
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  expectation_id uuid NOT NULL REFERENCES expectations(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  old_payload jsonb,
  new_payload jsonb,
  note text,
  actor_user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_expectation_events_expectation_id
  ON expectation_events (expectation_id, created_at DESC);

-- Raw composer lines ("recent" capture list)
CREATE TABLE IF NOT EXISTS ledger_captures (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  ledger_pillar integer NOT NULL,
  body text NOT NULL,
  parse jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ledger_captures_company_pillar_created
  ON ledger_captures (company_id, ledger_pillar, created_at DESC);
