-- Inled baseline schema
-- Agreed conventions:
-- - UUID PKs generated by gen_random_uuid()
-- - Semantic integer columns are app-defined (no CHECK constraints)
-- - Multi-company capable tenancy model

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Tenant root
CREATE TABLE IF NOT EXISTS companies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  domain text,
  created_by uuid,
  title text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_companies_domain
  ON companies (lower(domain))
  WHERE domain IS NOT NULL;


-- Invitation flow for joining companies
CREATE TABLE IF NOT EXISTS invites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  email text NOT NULL,
  role integer NOT NULL,
  status integer NOT NULL,
  token_hash text NOT NULL,
  invited_by_user_id uuid NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  accepted_at timestamptz,
  accepted_user_id uuid
);

CREATE INDEX IF NOT EXISTS idx_invites_company_id
  ON invites (company_id);

CREATE INDEX IF NOT EXISTS idx_invites_email
  ON invites (email);

-- People are the core identity model:
-- every member or collaborator is a person; auth link is optional.
CREATE TABLE IF NOT EXISTS people (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  email text,
  display_name text NOT NULL,
  handle text NOT NULL,
  title text,
  auth_user_id uuid,
  role integer NOT NULL DEFAULT 0,
  status integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_people_company_id
  ON people (company_id);

CREATE INDEX IF NOT EXISTS idx_people_handle
  ON people (handle);

CREATE INDEX IF NOT EXISTS idx_people_auth_user_id
  ON people (auth_user_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_people_company_email
  ON people (company_id, lower(email))
  WHERE email IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_people_company_handle
  ON people (company_id, lower(handle));

-- Unified ledger line:
-- one directed commitment tracked in the accountability ledger.
CREATE TABLE IF NOT EXISTS expectations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  writer_user_id uuid NOT NULL,
  target_person_id uuid REFERENCES people(id) ON DELETE RESTRICT,
  title text NOT NULL,
  summary text NOT NULL,
  deadline_label text,
  deadline_at timestamptz,
  finished_at timestamptz,
  responsible_updated_at timestamptz,
  last_chatted_sender_at timestamptz,
  last_chatted_receiver_at timestamptz,
  progress integer,
  expectation_status integer NOT NULL,
  expectation_health integer NOT NULL DEFAULT 0,
  expectation_type integer NOT NULL DEFAULT 0,
  expectation_visibility integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_expectations_company_writer
  ON expectations (company_id, writer_user_id);

CREATE INDEX IF NOT EXISTS idx_expectations_company_target
  ON expectations (company_id, target_person_id);

CREATE INDEX IF NOT EXISTS idx_expectations_company_status
  ON expectations (company_id, expectation_status);

ALTER TABLE expectations
  ADD COLUMN IF NOT EXISTS finished_at timestamptz,
  ADD COLUMN IF NOT EXISTS responsible_updated_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_chatted_sender_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_chatted_receiver_at timestamptz,
  ADD COLUMN IF NOT EXISTS expectation_health integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS expectation_type integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS update_requested_at timestamptz;

ALTER TABLE expectations
  ALTER COLUMN target_person_id DROP NOT NULL;

UPDATE expectations
SET expectation_type = 1
WHERE target_person_id IS NULL;

-- Reusable tag dictionary per company
CREATE TABLE IF NOT EXISTS expectation_tags (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_expectation_tags_company_name
  ON expectation_tags (company_id, lower(name));

-- Many-to-many relation: one expectation can have many tags
CREATE TABLE IF NOT EXISTS expectation_tag_links (
  expectation_id uuid NOT NULL REFERENCES expectations(id) ON DELETE CASCADE,
  tag_id uuid NOT NULL REFERENCES expectation_tags(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (expectation_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_expectation_tag_links_tag_id
  ON expectation_tag_links (tag_id);

-- Audit trail for commitment lifecycle transitions
CREATE TABLE IF NOT EXISTS expectation_events (
  id bigserial PRIMARY KEY,
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  expectation_id uuid NOT NULL REFERENCES expectations(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  old_payload jsonb,
  new_payload jsonb,
  note text,
  actor_user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_expectation_events_expectation_id
  ON expectation_events (expectation_id, created_at DESC);

-- Raw composer lines ("recent" capture list)
CREATE TABLE IF NOT EXISTS ledger_captures (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  ledger_pillar integer NOT NULL,
  body text NOT NULL,
  parse jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ledger_captures_company_pillar_created
  ON ledger_captures (company_id, ledger_pillar, created_at DESC);

-- Private sender/receiver chat per expectation (text first, optional attachments).
CREATE TABLE IF NOT EXISTS expectation_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  expectation_id uuid NOT NULL REFERENCES expectations(id) ON DELETE CASCADE,
  sender_person_id uuid NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
  -- 0 = chat (plain text), 2 = chat with file attachment(s); non-zero otherwise = changelog / activity:
  -- 1 = legacy plain text; 10–16 = structured JSON in message_text (see app expectation_changelog_payload.dart; 15 = update requested, 16 = receivers added).
  type smallint NOT NULL DEFAULT 0,
  message_text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_expectation_messages_expectation_created
  ON expectation_messages (expectation_id, created_at);

CREATE INDEX IF NOT EXISTS idx_expectation_messages_company_expectation
  ON expectation_messages (company_id, expectation_id);

CREATE TABLE IF NOT EXISTS expectation_message_attachments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  expectation_message_id uuid NOT NULL REFERENCES expectation_messages(id) ON DELETE CASCADE,
  file_name text NOT NULL,
  file_url text NOT NULL,
  mime_type text,
  file_size_bytes bigint,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_expectation_message_attachments_message_id
  ON expectation_message_attachments (expectation_message_id);

-- Per-message chat read receipts (counterparty opened thread).
CREATE TABLE IF NOT EXISTS expectation_message_reads (
  message_id uuid NOT NULL REFERENCES expectation_messages(id) ON DELETE CASCADE,
  reader_person_id uuid NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  read_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (message_id, reader_person_id)
);

CREATE INDEX IF NOT EXISTS idx_expectation_message_reads_reader
  ON expectation_message_reads (reader_person_id);

CREATE INDEX IF NOT EXISTS idx_expectation_message_reads_company
  ON expectation_message_reads (company_id);

-- Per-user "last seen" watermark for changelog rows on an expectation (app-updated only).
CREATE TABLE IF NOT EXISTS expectation_changelog_reads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  expectation_id uuid NOT NULL REFERENCES expectations(id) ON DELETE CASCADE,
  reader_person_id uuid NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  last_read_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (expectation_id, reader_person_id)
);

CREATE INDEX IF NOT EXISTS idx_expectation_changelog_reads_reader
  ON expectation_changelog_reads (reader_person_id);
